#!/bin/bash

set -euo pipefail

if [[ "${BUILDKITE_PLUGIN_TART_DEBUG:-false}" == "true" ]]; then
    set -x
fi

tart_user="${BUILDKITE_PLUGIN_TART_USER:-admin}"
tart_name="buildkite-job-id-${BUILDKITE_JOB_ID:-tart}"
tart_key="$HOME/.tart/vms/${tart_name}/workspace-key"
command="${BUILDKITE_COMMAND:-sw_vers}"

# Default path for automatic mounts
workspace="/Volumes/My Shared Files/workspace"

# Find the address of our guest
guest_ip=$(tart ip "${tart_name}")

# Execute build step command over ssh
ssh \
    -q \
    -o StrictHostKeyChecking=no \
    -o UserKnownHostsFile=/dev/null \
    -o ConnectTimeout=5s \
    -o IdentitiesOnly=yes \
    -i "${tart_key}" \
    "${tart_user}@${guest_ip}" \
    "pushd \"${workspace}\"; ${command}"
