#!/bin/bash

if [[ "${BUILDKITE_PLUGIN_TART_DEBUG:-false}" =~ ^(true|on|1)$ ]]; then
    set -euxo pipefail
fi

tart_user="${BUILDKITE_PLUGIN_TART_USER:-admin}"
tart_name="buildkite-job-id-${BUILDKITE_JOB_ID:-tart}"
command="${BUILDKITE_COMMAND:-sw_vers}"

PWD=$(dirname -- "$(readlink -f -- "$0")")
TART="/Applications/tart.app/Contents/MacOS/tart"
workspace="/Volumes/My Shared Files/workspace"

guest_ip=$($TART ip "${tart_name}")

ssh \
    -q \
    -o StrictHostKeyChecking=no \
    -o UserKnownHostsFile=/dev/null \
    -o ConnectTimeout=5s \
    -i "$HOME/.tart/vms/${tart_name}/buildkite-workspace-ecdsa" \
    "${tart_user}@${guest_ip}" \
    "pushd \"${workspace}\"; ${command}; popd"
