#!/bin/bash

set -e

if [[ "${BUILDKITE_PLUGIN_TART_DEBUG:-false}" =~ ^(true|on|1)$ ]]; then
    set -euxo pipefail
fi

default_tart_source="ghcr.io/cirruslabs/macos-ventura-base:latest"

tart_source="${BUILDKITE_PLUGIN_TART_IMAGE:-$default_tart_source}"
tart_cpus="${BUILDKITE_PLUGIN_TART_CPUS:-2}"
tart_memory="${BUILDKITE_PLUGIN_TART_MEMORY:-4096}"
tart_user="${BUILDKITE_PLUGIN_TART_USER:-admin}"
tart_password="${BUILDKITE_PLUGIN_TART_PASSWORD:-admin}"
tart_name="buildkite-job-id-${BUILDKITE_JOB_ID:-tart}"

script_root=$(dirname -- "$(readlink -f -- "$0")")
checkout_path="${BUILDKITE_BUILD_CHECKOUT_PATH:-}"

TART="/Applications/tart.app/Contents/MacOS/tart"

# if [[ $(ps aux | grep "[/]tart\ run" -c) -ge 2 ]]; then
#     echo "ERROR: The maximum supported number of active virtual machines has been reached."
#     exit 127
# fi

$TART clone "${tart_source}" "${tart_name}"
$TART set "${tart_name}" --cpu "${tart_cpus}" --memory "${tart_memory}"

nohup $TART run \
    --no-graphics \
    --net-softnet \
    --dir=workspace:"${checkout_path}" \
    "${tart_name}" \
    >/dev/null 2>/dev/null \
    &

sleep 10

guest_ip=$($TART ip "${tart_name}")

ssh-keygen -f "$HOME/.tart/vms/${tart_name}/buildkite-workspace-ecdsa" -t ecdsa -b 521 -P "" -q

expect -f <(cat << "EOF"

lassign $argv ip user password keypath

set timeout 15

spawn ssh-copy-id \
    -f \
    -i "${keypath}" \
    -o StrictHostKeyChecking=no \
    -o UserKnownHostsFile=/dev/null \
    -o ConnectTimeout=5s \
    -o PreferredAuthentications=password \
    "${user}@${ip}"

expect {
    -re ".*assword:.*" {
        send "$password\r"
        exp_continue
    }

    -re ".*ERROR.*" {
        exit 1
    }

    eof {}
}
EOF
) ${guest_ip} ${tart_user} ${tart_password} "$HOME/.tart/vms/${tart_name}/buildkite-workspace-ecdsa" >/dev/null 2>/dev/null

sleep 5

ssh \
    -q \
    -o StrictHostKeyChecking=no \
    -o UserKnownHostsFile=/dev/null \
    -o ConnectTimeout=5s \
    -i "$HOME/.tart/vms/${tart_name}/buildkite-workspace-ecdsa" \
    "${tart_user}@${guest_ip}" \
    "sw_vers"
