#!/bin/bash

set -euo pipefail

if [[ "${BUILDKITE_PLUGIN_TART_DEBUG:-false}" == "true" ]]; then
    set -x
fi

tart_source="${BUILDKITE_PLUGIN_TART_IMAGE:-}"
tart_cpus="${BUILDKITE_PLUGIN_TART_CPUS:-2}"
tart_memory="${BUILDKITE_PLUGIN_TART_MEMORY:-4096}"
tart_user="${BUILDKITE_PLUGIN_TART_USER:-admin}"
tart_password="${BUILDKITE_PLUGIN_TART_PASSWORD:-admin}"
tart_name="buildkite-job-id-${BUILDKITE_JOB_ID:-tart}"
tart_key="$HOME/.tart/vms/${tart_name}/workspace-key"
checkout_path="${BUILDKITE_BUILD_CHECKOUT_PATH:-}"


# Apple forbids more than two concurrent instances of macos and enforces this in the virtualization framework
if [[ $(ps aux | grep "[/]tart\ run" -c) -ge 2 ]]; then
    echo "ERROR: The maximum supported number of active virtual machines has been reached."
    exit 127
fi

# Create our guest and configure cpu and memory
tart pull "${tart_source}"
tart clone "${tart_source}" "${tart_name}"
tart set "${tart_name}" --cpu "${tart_cpus}" --memory "${tart_memory}"

# Start the guest and fork the process to prevent it being killed when this script exits
nohup tart run \
    --no-graphics \
    --net-softnet \
    --dir=workspace:"${checkout_path}" \
    ${tart_name} \
    >/dev/null 2>/dev/null \
    &

# Wait for the guest to boot then grab the address
for i in {1..60}; do guest_ip=$(tart ip ${tart_name}) && break || sleep 1; done

# Generate and install an ssh key for running commands later
ssh-keygen -f "${tart_key}" -t ecdsa -b 521 -P "" -q
expect -f <(cat << "EOF"

lassign $argv ip user password keypath

set timeout 15

spawn ssh-copy-id \
    -f \
    -i "${keypath}" \
    -o StrictHostKeyChecking=no \
    -o UserKnownHostsFile=/dev/null \
    -o ConnectTimeout=5s \
    -o PreferredAuthentications=password \
    "${user}@${ip}"

expect {
    -re ".*assword:.*" {
        send "$password\r"
        exp_continue
    }

    -re ".*ERROR.*" {
        exit 1
    }

    eof {}
}
EOF
) ${guest_ip} "${tart_user}" "${tart_password}" "${tart_key}" >/dev/null 2>/dev/null

echo "Created ${tart_name} from ${tart_source}"
