#!/bin/bash

if [[ "${BUILDKITE_PLUGIN_TART_CLEANUP:-false}" =~ ^(true|on|1)$ ]]; then
    set -euxo pipefail
fi

tart_name="buildkite-job-id-${BUILDKITE_JOB_ID:-tart}"

if [[ "${BUILDKITE_PLUGIN_TART_CLEANUP:-true}" =~ ^(true|on|1)$ ]]; then
    echo "Removing ${tart_name}"
    tart stop "${tart_name}" || true
    tart delete "${tart_name}" || true
else
    echo "Stopping ${tart_name}"
    tart stop "${tart_name}" || true
fi
