steps:
  - label: ":wave: :apple:"
    agents:
      queue: "macos"
      tart: "true"
    plugins:
        - ./.buildkite/plugins/tart:
            cpus: 4
    command: |
      : do mac things...
      uptime
      sw_vers
      sysctl hw.model hw.ncpu
